import os
import json
from robyn import SubRouter, Response

document_router = SubRouter(__name__)

# The worker saves graph files in its own CWD. We look in a shared/known path.
# For local dev, we check GRAPH_STORAGE_DIR env var, defaulting to the worker's likely CWD.
GRAPH_STORAGE_DIR = os.environ.get("GRAPH_STORAGE_DIR", ".")


def _graph_path(document_id: str) -> str:
    return os.path.join(GRAPH_STORAGE_DIR, f"graph_{document_id}.json")


@document_router.get("/document/:id/status")
async def get_document_status(request):
    """
    Returns whether the AI processing for a document is complete.
    Checks for the existence of graph_{id}.json produced by the worker.
    """
    document_id = request.path_params.get("id")
    if not document_id:
        return Response(
            status_code=400,
            headers={"Content-Type": "application/json"},
            description=json.dumps({"error": "Missing document ID"}),
        )

    graph_file = _graph_path(document_id)

    if os.path.isfile(graph_file):
        return Response(
            status_code=200,
            headers={"Content-Type": "application/json"},
            description=json.dumps({"status": "completed", "document_id": document_id}),
        )
    else:
        return Response(
            status_code=200,
            headers={"Content-Type": "application/json"},
            description=json.dumps({"status": "processing", "document_id": document_id}),
        )


@document_router.get("/document/:id/graph")
async def get_document_graph(request):
    """
    Reads and returns the graph JSON generated by the AI worker.
    """
    document_id = request.path_params.get("id")
    if not document_id:
        return Response(
            status_code=400,
            headers={"Content-Type": "application/json"},
            description=json.dumps({"error": "Missing document ID"}),
        )

    graph_file = _graph_path(document_id)

    if not os.path.isfile(graph_file):
        return Response(
            status_code=404,
            headers={"Content-Type": "application/json"},
            description=json.dumps({"error": "Graph not found. Processing may still be in progress."}),
        )

    try:
        with open(graph_file, "r", encoding="utf-8") as f:
            graph_data = json.load(f)

        return Response(
            status_code=200,
            headers={"Content-Type": "application/json"},
            description=json.dumps(graph_data),
        )
    except Exception as e:
        return Response(
            status_code=500,
            headers={"Content-Type": "application/json"},
            description=json.dumps({"error": str(e)}),
        )
